### ISSUE TITLE
3.0.0 Goals

### ISSUE THREAD

**Issue by evertiro** [evertiro/historical-redux2#138]
- [x] Fix undefined index errors - #136 
- [x] Fix Raw HTML content type - #132
- [x] Add hook before saving - #120 
- [x] Add handler for variable name/location configs - #119 
- [x] Better documentation
- [x] Conditional fields
- [x] Support HTML5 input types and elements - #143

**Comment by evertiro** [comment]
I'm planning on releasing v3.0.0 soon, and with it is going to come a major overhaul to the core of Redux. Lots of things are going to change (hopefully mostly for the better), and I'd like your opinions! As indicated above, a few long-standing issues are being fixed, but that's just the beginning! I'm also making it possible for you to store the config file whatever you want and seamlessly pass it back to the framework, which should make life much simpler in terms of upgrading (particularly for those who are pulling straight from Github). I'm also considering two major changes to the structure of the config file itself. Any feedback you can provide would be greatly appreciated.

#### Issue 1

Right now adding an option goes something like this... You have an array for $sections, which contains an array called $fields, which contains individual arrays for each field as such...

``` PHP
array(
    'id' => 'text_demo',
    'type' => 'text',
    'title' => __( 'Text Option', Redux_TEXT_DOMAIN ),
    'sub_desc' => __( 'Sub description goes here', Redux_TEXT_DOMAIN ),
    'desc' => __( 'Description goes here', Redux_TEXT_DOMAIN ),
);
```

My proposal is to rework the system such that new fields would be created as follows:

``` PHP
$text_demo = new textField(
    'text_demo',
    __( 'Text Option', Redux_TEXT_DOMAIN ),
    __( 'Sub description', Redux_TEXT_DOMAIN ),
    __( 'Description', Redux_TEXT_DOMAIN )
);
```

Obviously, this is just a mockup of what I'm considering, but what does the community think? Would making the system more object oriented be beneficial? Would it make it cleaner/easier? I don't know!

#### Issue 2

My second question is in how data is stored... Right now, you would access the variable mentioned in issue 1 as follows:

``` PHP
global $redux_options;
$redux_options = get_option( 'my_redux_options' );

echo $redux_options['text_demo'];
```

But what if you could do something like this:

``` PHP
global $redux_options;
$redux_options = get_option( 'my_redux_options' );

echo $redux_options['section1']['text_demo'];
```

Would being able to reference a specific sections data independently be worth adding? What about just the ease of use afforded by compartmentalizing individual options? With this method, say you were developing a social media plugin... you could actually do something like this:

``` PHP
global $redux_options;
$redux_options = get_option( 'my_redux_options' );

...

function facebook_stuff() {
    global $redux_options;
    $facebook_options = $redux_options['facebook'];

    echo $facebook_options['username'];
}

function twitter_stuff() {
    global $redux_options;
    $twitter_options = $redux_options['twitter'];

    echo $twitter_options['username'];
}
```

Being able to use the variable 'username' as in the above demo seems preferable to me to having `$redux_options['twitter_username']` and `$redux_options['facebook_username']`, or am I overthinking this? Thoughts? Comments? Suggestions?

**Comment by bhi-archive** [comment]
Personally I like the way it is now in Issue 1.

array(
    'id' => 'text_demo',
    'type' => 'text',
    'title' => __( 'Text Option', Redux_TEXT_DOMAIN ),
    'sub_desc' => __( 'Sub description goes here', Redux_TEXT_DOMAIN ),
    'desc' => __( 'Description goes here', Redux_TEXT_DOMAIN ),
);

is more in line with how I would expect the framework to function within
the terms of how WP core uses the Settings API

I get where you are going within Issue 2,  but I like the way Redux is now.

_Chad_

**Comment by evertiro** [comment]
Ok, that's one vote for keeping things the way they are. Anyone else want to chime in?

**Comment by psaikali** [comment]
I'd like to add my own 2 cents here ! I would agree with your first post, I think it'll be better if we had an "easier" and more functional access to some function or class to define the settings page and add fields.

I'm using the Cuztom Helper to create post types, taxonomies and metaboxes and they use this approach to add fields (https://github.com/Gizburdt/Wordpress-Cuztom-Helper/blob/master/readme.md).

Something like ...

``` php
$setting_page = new Redux_Page( array( $settings ) );
```

Could allow us to do ...

``` php
$setting_page->add_section(...);

$setting_page->add_field(...);
```

You get the idea.

I think it's way more flexible than the current way, we could load sections & fields conditionally.

Hope my 2 cents helped ;) Thx for your hard work anyway.

**Comment by evertiro** [comment]
Interesting idea. Let's see if anyone else wants to chime in!

**Comment by tivnet** [comment]
Issue 1: not the way you suggested
Even with OOP, it still has to be 

```
$text_demo = new textField( array(....) );
```

because some of the parameters can be omitted, I think

Issue 2: As long as you provide the backward compatibility. Not very important, but can be useful.

Whatever you change, all the hooks, like the original `nhp-opts-sections-` must be kept, so a theme and several plugins can use the same option screen.

Thank you!

**Comment by evertiro** [comment]
@tivnet 
Issue 1... fair enough, I suppose I was just envisioning using null for skipped params, but that's a good point.
Issue 2... hooks and such would end up being expanded on, not removed... although I don't believe I have anything left with the old `nhp-*` naming scheme anymore...

**Comment by tivnet** [comment]
Yes, of course, `redux-opts-sections-`

**Comment by luthfanali** [comment]
Can you make section inside section?

**Comment by evertiro** [comment]
Can you elaborate?

**Comment by luthfanali** [comment]
Maybe, looks like this.
Inside textfield section we have some sub section
![ilustration](https://f.cloud.github.com/assets/5035521/816653/eef3fb6c-ef4f-11e2-9fc6-ff481dbee13c.jpg)

I edited the image. Just for example ;)

**Comment by evertiro** [comment]
Wow... that'd definitely be cool but it'd be a major change. Although... that's what major version updates are for! Thoughts from the userbase? Is it worth making this kind of change?

**Comment by tivnet** [comment]
On Issue 2: (my previous message was not clear, because I mixed two topics in one, sorry)
So, instead of

```
$sections[] = array(
    'fields'     => array(
        array(
            'id'    => 'facebook_username',
```

There will be

```
$sections['facebook'] = array(
    'fields'     => array(
        array(
            'id'    => 'username',
```

and then instead of

```
$fbusername = get_options(...)['facebook_username']
```

we will have

```
$fbusername = get_options(...)['facebook']['username']
```

I think it can be useful for sections with mostly repeated fields. Do you know how to make this change, and still keep the existing way, for backward compatibility?

**Comment by cyberwani** [comment]
+1  @luthfan I agree with the idea.

**Comment by cyberwani** [comment]
Adding the repeatable field can be more useful.

**Comment by corradomatt** [comment]
This is a great options framework...here are my thoughts....

Issue #1 - I like the idea of OOP with the framework but I think that keeping the settings arrays the way they are now is good. As bluehiveinteractive and tivnet pointed out it is more inline with what WordPress is doing with their options settings.

Issue #2 - I think that tying the data to sections is a good idea. It makes things easier to work with when there are lots of sections and repeating options in those sections.

luthfan suggestion - I like the idea of allowing multiple tabbed sections within sections - sometimes options pages can be too long when there are lots of options under 1 section. Another idea I've had is to rework the table layout of the options page. Instead of tables we could use standard markup which would allow us to take advantage of a column layout and have 2 or even 3 options side-by-side if needed.

**Comment by peter-nl** [comment]
Some thoughts for 3.0.0 Goals in order of appearance above:
- hook before saving is a good idea. Can't the standard WP filter 'pre_update_option_(option_name)' be used?
- documentation: i always wonder what the status is of http://plovs.github.io/Redux-Framework-Docs/index.html; would that not be a good start for docu?
- issue 2 data storage; i guess this would be an extention to the current data storage? imo it should remain possible to retrieve a field value just by it's id; always having to pass a section id would be overhead.
- like @psaikali i think functions to simply add sections and fields are useful. This can be fairly easily achieved with some additional filters, I believe.
- +1 for the repeatable field

And in addition: 
- futher to the fields definition and storage; there could be an option to make fields depend on the value of other fields. This is particularly useful in conjunction with the hide_below fields. I believe there's an issue that deals with this but ca'nt find that right now. 
- I've been working with the Theme customizer lately and this is a very strong feature. One way or the other,  Redux should really hook into that development. Also ref https://github.com/ghost1227/Redux-Framework/issues/56.
- Addition of Multisite support (and maybe some more plugin support in general). 

Thx for all the effort you put into Redux!

**Comment by Pushplaybang** [comment]
I have to say that I do like the section fields they way they are now, and maybe I'm not knowledgable enough to understand but I haven't seen any convincing argument for why it would be better.  

What kind of new and shiny flexibility would it allow ?    

Regarding being able to call items via section specific id, such as `$options['section_name']['op_ID']`   again I'm not sure what this would allow us to do, other than use duplicate id's which I just don't think are a good idea. Not having the section ID's means its quicker to re arrange options without having to change the ID in multiple places.

If there are valid reasons, I'd love to know what they are, so I could  understand how these would affect the framework as a whole.

Loved NHP, loving redux more, and Looking forward to the next update, great work @ghost1227

**Comment by evertiro** [comment]
@tivnet 

Backwards compatibility would not be affected, if we decided to go that route.

@corradomatt 

Issue 1: My preference to maintaining the visual appearance of WordPress core itself notwithstanding, I'm not necessarily against modifying how developers interact with the framework if it provides a simple, cleaner, or easier to understand environment.

Issue 2: My thoughts exactly.

@peter-nl 

First, documentation (in some complete form) will be included with the release of V3. I also intend to redo the website to be a bit more complete.

Backwards compatibility will obviously be maintained. I know how much of a pain it would be to convert my own work, let alone that of all my users!

In terms of making fields dependent on the value of other fields, I think that's actually a great idea! I'll add it to the V3 todo list!

I'd also love to integrate with customizer but I'm a bit out of my league on that particular task. For one, Redux was designed specifically to be as useful for plugin devs as theme devs... I've never even personally used it in a theme! I'm not sure how best to handle it such that it's available for themes, but not hooked at all for plugins. Also, as I am predominantly a plugin developer, I have almost literally no experience with customizer... any tips or help would certainly be appreciated!

Multisite support is in the works (honestly didn't know it didn't work until a user submitted a bug on one of my plugins that uses Redux), as for other plugins... thoughts as to what else is popular/common use enough to warrant inclusion?

@Pushplaybang 

It's all perspective. Personally, I've always favored OOP, but since NHP wasn't OOP I never bothered to convert it. Beyond my personal preferences, there is some small amount of flexibility gained through making Redux a truly class-based system, most notably there would be less issues with conflict.

Right now, if you installed one of my plugins using Redux, as well as a theme using Redux, unless one of us has changed the name of the wrapper function, they will conflict. Making it class based would make it easier for devs to instantiate their own instance of Redux without the chance of conflict with another system using it.

Additionally, if I wrote it right, it would have the benefit of being easily extensible programmatically. What this means is that we can start offering actual extensions to Redux that would permit addition of new features that aren't common enough to be included in core. Inversely, we could also theoretically remove unneeded functionality to minimize the footprint of the platform.

Regarding the section specific ID issue, I would maintain backwards compatibility so you could continue to use the traditional method at your discretion. However, I think that while it's not always a GREAT idea to duplicate IDs, there are some situations in which it actually simplifies things. Take for example, social media. It seems to me that being able to store options as `$options['twitter']['url']` and `$options['header']['title']` would make it much easier to remember and/or categorize options... keeping those for Twitter separate from those relevant to the header of a page for example.

## 

Too all who gave their thoughts so far, and especially those who gave praise for the framework, thanks for everything! It's all my awesome users that make this project worthwhile!

**Comment by tridungpham** [comment]
@ghost1227 :+1:  thank you for your work with Redux. I like this framework a lot. 
About version 3.0, I don't know if anyone suggested this before, but I think you should add a function/button next to each field/option that can restore that field/option back to its default value (or its previous value).

**Comment by evertiro** [comment]
@tridungpham We actually played with that once... default value is possible, but kinda finicky. Previous value would require doubling up the database size, so I'm not likely to go that route... Might try to work in a better reset to defaults system though!

**Comment by tonibecker** [comment]
@ghost1227 awesome work on the Framework. Some little input from 10 years of wordpress dev :)
It would be great if you could implement the tabbed section feature shown in the screenshot from @luthfan . One nice part would be the implementation for the custom meta boxes used inside redux for posts/pages. That would be stunning awesome feature. One last could be the integration of a click and build generate sidebar as shown in the screenshot. 
![sidebar-gui](https://f.cloud.github.com/assets/2493214/974034/f096a096-0647-11e3-868c-4b8b085cf526.png)

**Comment by dovy** [comment]
@tonibecker That's a personal plan of mine, eventually. May take some time.

Tabs we're on the fence about, but may implement.
